name: Devlopement
author: Dams333
version: 3.0.0
main: ch.dams333.devlopement.Devlopement
api-version: 1.13
commands:
  devmod:
    decription: Entrer ou quitter le mode de developpement
    permission: devlopement.commands.admin.devmod
  devitems:
    description: Ouvrir les items de developpement
    permission: devlopement.commands.admin.devitems
  message:
    decription: Gerer vos messages
    permission: devlopement.commands.admin.message
  location:
    description: Gerer vos locations
    permission: devlopement.commands.admin.location
  link:
    description: Permet de lier une condition a un si non
    permission: devlopement.commands.admin.link
  variable:
    description: Permet de gerer les variables
    permission: devlopement.commands.admin.variable
  timer:
    description: Permet de gerer les timers
    permission: devlopement.commands.admin.timer